### ISSUE TITLE
Support for JSON Schema simplification?

### ISSUE THREAD

**Issue by jechterhoff** [jimblackler/jsonschemafriend#27]
Hi,

Out of curiosity, since the documentation states that parsing a JSON Schema is supported: Does this tool include a feature that allows simplification of a given JSON Schema? With simplification, I mean merging all allOf constraints (and possibly de-referencing any schema references). I know that some other software tools exist that claim to support that kind of simplification, and that this is a non-trivial task. I am just interested to know if jsonschemafriend has something in this area.

Background: We have a schema that makes extensive use of allOf, but some (non-validator) tools which we would like to feed that schema do not support allOf.

Cheers,
Johannes

**Comment by jechterhoff** [comment]
... and/or is it possible to load a schema and have all $ref entries resolved - with support for references that contain a plain JSON Pointer as fragment identifier, as well as references that use JSON Schema anchors as fragment identifier? Recursive / circular / missing references would need to be handled somehow...

**Comment by kool79** [comment]
> merging all allOf constraints

It is impossible in some cases. Example below:
```
 allOf:[
  {  
     if: {properties: {country: {enum: "UA", "UK"}}},
     then: {required: ["zipCode"]} 
  },{
     if: {properties: {country: {enum: "US", "CA"}}},
     then: {required: ["state"]} 
  }
]  
```
>is it possible to load a schema and have all $ref entries resolved

look at the last example in readme. It actually resolves all $ref entries.

**Comment by jechterhoff** [comment]
Thank you very much. That information is helpful.
