### ISSUE TITLE
type: integer does not match specification

### ISSUE THREAD

**Issue by kool79** [jimblackler/jsonschemafriend#39]
Specifications (since draft-6) say (https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-01#name-mathematical-integers): 
 **_For consistency, integer JSON numbers SHOULD NOT be encoded with a fractional part._**  (should not == not recommended)
 But both the properties in json below matches to `{"type": "integer"}`
 ```
 { "a": 5,
   "b": 5.0
 }
 ```
 while the only integer property is the "a"
 Note thal library works in expected way when I select draft-3 or draft-4 here: https://tryjsonschematypes.appspot.com/#validate

**Comment by jimblackler** [comment]
I concur with your assesment of the standard and that the online demo is not exhibiting the correct behavior.

The relevant official test is "a float with zero fractional part is an integer". https://github.com/python-jsonschema/jsonschema/blob/b307f310f86b191dd266bfba1de0eea61f0ee194/json/tests/draft2020-12/type.json#L15C33-L15C80

This test *does* pass in this project so more investigation is needed.

**Comment by jimblackler** [comment]
The official test is caled "a float with zero fractional part is an integer"

https://github.com/python-jsonschema/jsonschema/blob/b307f310f86b191dd266bfba1de0eea61f0ee194/json/tests/draft2019-09/type.json#L15

This seems to suggest that `b: 5.0` should pass.

**Comment by kool79** [comment]
Thanks for link. Actually it is not logical from many points of views, but standard is the standard, even if it is not logical.

By the way, with other library I used 
{type: number, multipleOf: 1.0} for 5.0 and {type: integer} for 5
