### ISSUE TITLE
SchemaStore enters infinite loop when $schema returns no content

### ISSUE THREAD

**Issue by lizjackson-toast** [jimblackler/jsonschemafriend#43]
Loading a JSON schema through a `SchemaStore` object results in an infinite loop if a JSON schema has a `$schema` that has no content (such as http://json-schema.org/schema, which returns a 301) and also does not have an `$id`.

Here's how this happens:

1. We enter a `while (true)` loop [here](https://github.com/jimblackler/jsonschemafriend/blob/2c17347126373da5d1a57d8cd3bbd76f1c97d57a/library/src/main/java/net/jimblackler/jsonschemafriend/SchemaStore.java#L144).
2. Then we try getting content from the `$schema` [here](https://github.com/jimblackler/jsonschemafriend/blob/2c17347126373da5d1a57d8cd3bbd76f1c97d57a/library/src/main/java/net/jimblackler/jsonschemafriend/SchemaStore.java#L161) and `content` is null.
3. The `store` call [here](https://github.com/jimblackler/jsonschemafriend/blob/2c17347126373da5d1a57d8cd3bbd76f1c97d57a/library/src/main/java/net/jimblackler/jsonschemafriend/SchemaStore.java#L163) throws an exception due to the null content.
4. We catch this exception in the `catch (JsonProcessingException e)` [block](https://github.com/jimblackler/jsonschemafriend/blob/2c17347126373da5d1a57d8cd3bbd76f1c97d57a/library/src/main/java/net/jimblackler/jsonschemafriend/SchemaStore.java#L164).
5. Then we make a `Document` object called `doc` and an `Elements` object called `links` [here](https://github.com/jimblackler/jsonschemafriend/blob/2c17347126373da5d1a57d8cd3bbd76f1c97d57a/library/src/main/java/net/jimblackler/jsonschemafriend/SchemaStore.java#L169-L170). However, since `content` is null, `doc` is null and `links` has a size of zero.
6. As a result, we never set `resolved` to `true` [here](https://github.com/jimblackler/jsonschemafriend/blob/2c17347126373da5d1a57d8cd3bbd76f1c97d57a/library/src/main/java/net/jimblackler/jsonschemafriend/SchemaStore.java#L175-L179) because there are no `links` to loop through, and we display the "Was not valid JSON" warning from [this block](https://github.com/jimblackler/jsonschemafriend/blob/2c17347126373da5d1a57d8cd3bbd76f1c97d57a/library/src/main/java/net/jimblackler/jsonschemafriend/SchemaStore.java#L181-L183).
7. Then we `continue` [here](https://github.com/jimblackler/jsonschemafriend/blob/2c17347126373da5d1a57d8cd3bbd76f1c97d57a/library/src/main/java/net/jimblackler/jsonschemafriend/SchemaStore.java#L185), loop again, hit the same problem, and keep looping ad infinitum.

Even though the jsonschemafriend [readme](https://github.com/jimblackler/jsonschemafriend/tree/2c17347126373da5d1a57d8cd3bbd76f1c97d57a#about) lists a specific set of schemas that are supported in the `$schema` field, jsonschemafriend should throw an exception if the `$schema` has no content rather than looping infinitely.

Let me know if you'd like me to fix this myself or if someone closer to jsonschema friend would prefer to address this.

Thank you!

**Comment by jimblackler** [comment]
Thanks for the report and all the detective work.

If you do want to fix it yourself I'll take the patch, that would probably be faster than waiting for me to do it, given that I'm juggling about five projects at the moment.

**Comment by lizjackson-toast** [comment]
You know what – turns out we resolved this issue by upgrading from `0.11.4` to `0.12.2`. No updates are needed after all; thanks for adding the latest updates!
