### ISSUE TITLE
caching a schema in the temporary folder could be optional

### ISSUE THREAD

**Issue by zak905** [jimblackler/jsonschemafriend#7]
It seems like a downloaded schema is saved in the system temp folder as defined in the CacheLoader class:

https://github.com/jimblackler/jsonschemafriend/blob/master/library/src/main/java/net/jimblackler/jsonschemafriend/CacheLoader.java#L19

I think it would be great if the user can choose whether to cache or not, based on whether the schema changes frequently. For example, it could be done using java property. I can submit a PR

**Comment by jimblackler** [comment]
Sure. I would prefer to have that configured in the SchemaStore constructor however.

The main motivation for it is for the metaschema verification (checking the schema is valid); this will always involve an http fetch if there's no caching. Of course we could also allow skipping of the metaschema verify.

**Comment by zak905** [comment]
Just submitted #8, how does it sound ? Happy to adjust if there are any suggestions

**Comment by zak905** [comment]
Oh thanks, for the quick feedback:) when is the next release planned

**Comment by jimblackler** [comment]
Thanks for the patch.

I made a release 0.10.6. Let me know if you have issues.

Jim

**Comment by zak905** [comment]
Awesome thank you
