### ISSUE TITLE
reasons why getMessage() method is not publicly accessible

### ISSUE THREAD

**Issue by zak905** [jimblackler/jsonschemafriend#9]
Hi,

I am just thinking that it could be useful to have `getMessage()` publicly accessible: https://github.com/jimblackler/jsonschemafriend/blob/master/library/src/main/java/net/jimblackler/jsonschemafriend/ValidationError.java#L51

 I just had a case today where the message need to be customized and I had to use reflection to obtain the result of `getMessage()`

**Comment by jimblackler** [comment]
Pure oversight. I have made it public for the next release.

**Comment by zak905** [comment]
great thanks!
